--- #YAML:1.0
name:                Acme-Murphy
version:             1.00
abstract:            If anything can go wrong, it will.
license:             ~
author:              
    - Mirko Westermeier <memowe@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
